"""Extract .prose content from modal HTML pages into modal-pages-data.js for file:// opens."""
from pathlib import Path
import json
import re

root = Path(__file__).resolve().parent
files = [
    "how-it-works.html",
    "about-us.html",
    "why-choose-us.html",
    "questions.html",
    "definitions.html",
    "rates-fees.html",
    "unsubscribe.html",
    "contact.html",
    "privacy-policy.html",
    "terms-of-use.html",
    "disclaimer.html",
    "advertising-disclosure.html",
    "do-not-sell-my-info.html",
]


def extract_prose(html: str):
    for marker in ('class="prose wide"', "class='prose wide'", 'class="prose"', "class='prose'"):
        idx = html.find(marker)
        if idx < 0:
            continue
        open_tag = html.rfind("<div", 0, idx)
        if open_tag < 0:
            continue
        start = html.find(">", idx) + 1
        i = start
        depth = 1
        while i < len(html) and depth:
            next_open = html.find("<div", i)
            next_close = html.find("</div>", i)
            if next_close < 0:
                break
            if next_open >= 0 and next_open < next_close:
                depth += 1
                i = next_open + 4
            else:
                depth -= 1
                if depth == 0:
                    return html[start:next_close].strip()
                i = next_close + 6
    return None


def main():
    out = {}
    for name in files:
        html = (root / name).read_text(encoding="utf-8")
        prose = extract_prose(html)
        status = "OK" if prose else "FAIL"
        print(f"{name}: {status} ({len(prose) if prose else 0})")
        if prose:
            # Strip leading page-hero duplicates if any leaked — keep FAQ intro as-is
            out[name] = prose

    js_path = root / "modal-pages-data.js"
    lines = [
        "/* Offline modal HTML for file:// opens. Regenerated by _build_modal_data.py */",
        "window.IFIND_MODAL_HTML = {",
    ]
    for key, value in out.items():
        lines.append(f"  {json.dumps(key)}: {json.dumps(value)},")
    lines.append("};")
    js_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {js_path} ({js_path.stat().st_size} bytes, {len(out)} pages)")


if __name__ == "__main__":
    main()
